# Generated by Django 4.0.3 on 2022-03-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
