# Generated by Django 4.0.3 on 2022-03-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
